//! Generates the engine's Unicode tables from the UCD data vendored in `ucd/`.
//!
//! `deny.toml` bans `unicode-width` and `unicode-segmentation`, so the engine carries its own
//! tables. Nothing above this file may ask a crate what a grapheme cluster is.
//!
//! Three properties are emitted, each as a three-stage trie in the shape `unicode-width`'s
//! generated source uses — root index, middle index, packed leaves — because it is `O(1)` with no
//! binary search anywhere on the path. `unicode-segmentation`'s coarse-index-plus-binary-search
//! hybrid is larger *and* slower and is deliberately not copied.
//!
//! | table | bits/codepoint | what it answers |
//! |---|---|---|
//! | `BREAK` | 4 | `Grapheme_Cluster_Break`, for UAX #29 |
//! | `AUX` | 4 | `Indic_Conjunct_Break`, `Extended_Pictographic`, `Emoji` — the rest of UAX #29, and the VS16 base test |
//! | `WIDTH` | 2 | the column count of one codepoint, from UAX #11 plus emoji presentation |
//!
//! The stage shape of each table is not chosen dogmatically: the generator builds every candidate
//! split and keeps the smallest, which is the discipline `rust-lang/rust`'s own
//! `unicode-table-generator` applies per property.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// The UCD release these tables are generated from, stated once.
///
/// Every vendored file is checked to declare this version before a byte of it is parsed, so a
/// half-updated `ucd/` directory is a build failure rather than a table that silently mixes two
/// Unicode releases.
const UCD_VERSION: &str = "17.0.0";

/// One past the last Unicode code point.
const CODESPACE: usize = 0x11_0000;

fn main() {
    let ucd = PathBuf::from(env("CARGO_MANIFEST_DIR")).join("ucd");

    let files = [
        "GraphemeBreakProperty.txt",
        "DerivedCoreProperties.txt",
        "emoji-data.txt",
        "EastAsianWidth.txt",
        "DerivedGeneralCategory.txt",
        "GraphemeBreakTest.txt",
    ];
    for f in files {
        println!("cargo::rerun-if-changed={}", ucd.join(f).display());
        check_version(&ucd.join(f));
    }
    println!("cargo::rerun-if-changed=build.rs");

    let breaks = break_classes(&ucd);
    let aux = aux_classes(&ucd);
    let width = width_classes(&ucd);

    let mut out = format!(
        "\
// Generated by build.rs from the Unicode Character Database {UCD_VERSION}.
// Do not edit: edit build.rs, or the data in crates/vitui-engine/ucd/.

/// The UCD release these tables were generated from.
pub(crate) const UCD_VERSION: &str = \"{UCD_VERSION}\";

"
    );

    emit(&mut out, "BREAK", "break_class", 4, &breaks);
    emit(&mut out, "AUX", "aux_class", 4, &aux);
    emit(&mut out, "WIDTH", "width_class", 2, &width);

    let dest = Path::new(&env("OUT_DIR")).join("ucd_tables.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("cannot write {}: {e}", dest.display()));
}

// ---------------------------------------------------------------------------------------------
// The vendored data
// ---------------------------------------------------------------------------------------------

/// Fails the build unless the file's own header declares [`UCD_VERSION`].
///
/// `emoji-data.txt` is the odd one out: it carries `# Version: 17.0` rather than the
/// `<Name>-17.0.0.txt` first line every other UCD file uses.
fn check_version(path: &Path) {
    let text = read(path);
    let head: String = text.lines().take(20).collect::<Vec<_>>().join("\n");
    let short = UCD_VERSION
        .rsplit_once('.')
        .map(|(major_minor, _)| major_minor)
        .unwrap_or(UCD_VERSION);
    // A whole-line match, not a substring: `# Version: 17.0` must not accept a 17.0.1 file.
    let stamped = head.contains(&format!("-{UCD_VERSION}.txt"))
        || text.lines().take(20).any(|line| {
            let line = line.trim();
            line == format!("# Version: {UCD_VERSION}") || line == format!("# Version: {short}")
        });
    assert!(
        stamped,
        "{} does not declare UCD {UCD_VERSION} in its header; the vendored data is out of step \
         with build.rs's UCD_VERSION",
        path.display()
    );
}

/// One of the variables cargo sets for a build script.
fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|e| panic!("cargo did not set {key}: {e}"))
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read vendored UCD file {}: {e}", path.display()))
}

/// One line of a UCD property file: a code point range and its semicolon-separated fields.
struct Row {
    first: u32,
    last: u32,
    fields: Vec<String>,
}

/// Parses the shared UCD property-file format: `range ; field ; field  # comment`.
fn rows(path: &Path) -> Vec<Row> {
    let text = read(path);
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.split('#').next().unwrap_or_default().trim();
        if line.is_empty() {
            continue;
        }
        let mut fields = line.split(';').map(|f| f.trim().to_owned());
        let range = fields.next().unwrap_or_default();
        let (first, last) = match range.split_once("..") {
            Some((a, b)) => (hex(a), hex(b)),
            None => (hex(&range), hex(&range)),
        };
        out.push(Row {
            first,
            last,
            fields: fields.collect(),
        });
    }
    out
}

fn hex(s: &str) -> u32 {
    u32::from_str_radix(s.trim(), 16).unwrap_or_else(|e| panic!("bad code point {s:?}: {e}"))
}

/// Every code point carrying the boolean property `name`.
fn set_of(path: &Path, name: &str) -> Vec<bool> {
    let mut out = vec![false; CODESPACE];
    for row in rows(path) {
        if row.fields.first().map(String::as_str) != Some(name) {
            continue;
        }
        for cp in row.first..=row.last {
            out[cp as usize] = true;
        }
    }
    out
}

// ---------------------------------------------------------------------------------------------
// The three properties
// ---------------------------------------------------------------------------------------------

/// `Grapheme_Cluster_Break`, in the order `src/ucd.rs`'s `Break` enum declares.
const BREAK_NAMES: [&str; 14] = [
    "Other",
    "CR",
    "LF",
    "Control",
    "Extend",
    "ZWJ",
    "Regional_Indicator",
    "Prepend",
    "SpacingMark",
    "L",
    "V",
    "T",
    "LV",
    "LVT",
];

fn break_classes(ucd: &Path) -> Vec<u8> {
    let mut out = vec![0u8; CODESPACE];
    for row in rows(&ucd.join("GraphemeBreakProperty.txt")) {
        let name = row.fields.first().expect("no property value").as_str();
        let code = BREAK_NAMES
            .iter()
            .position(|n| *n == name)
            .unwrap_or_else(|| panic!("unknown Grapheme_Cluster_Break value {name:?}"))
            as u8;
        for cp in row.first..=row.last {
            out[cp as usize] = code;
        }
    }
    out
}

fn aux_classes(ucd: &Path) -> Vec<u8> {
    let emoji_data = ucd.join("emoji-data.txt");
    let ext_pict = set_of(&emoji_data, "Extended_Pictographic");
    let emoji = set_of(&emoji_data, "Emoji");

    let mut out = vec![0u8; CODESPACE];
    for row in rows(&ucd.join("DerivedCoreProperties.txt")) {
        if row.fields.first().map(String::as_str) != Some("InCB") {
            continue;
        }
        // Bits 0..1: Indic_Conjunct_Break. 0 is None, and None is the overwhelming majority, which
        // is what makes this table dedup down to almost nothing.
        let code = match row.fields.get(1).map(String::as_str) {
            Some("Consonant") => 1u8,
            Some("Extend") => 2,
            Some("Linker") => 3,
            other => panic!("unknown Indic_Conjunct_Break value {other:?}"),
        };
        for cp in row.first..=row.last {
            out[cp as usize] = code;
        }
    }
    for cp in 0..CODESPACE {
        // Bit 2: Extended_Pictographic, for GB11. Bit 3: Emoji, which is what decides whether a
        // VS16 in a cluster means anything — `#` is Emoji and not Extended_Pictographic, and the
        // keycap sequence `#\u{FE0F}\u{20E3}` is exactly the case that separates the two.
        out[cp] |= u8::from(ext_pict[cp]) << 2;
        out[cp] |= u8::from(emoji[cp]) << 3;
    }
    out
}

/// The columns one code point occupies: 0 zero, 1 narrow, 2 wide.
///
/// Ambiguous-width (UAX #11 class `A`) resolves to **narrow**. UAX #11 disclaims terminal use of
/// the property outright and every terminal tailors it; narrow is what `unicode-width` and
/// wezterm both default to, so it is the answer that disagrees with the fewest terminals.
fn width_classes(ucd: &Path) -> Vec<u8> {
    let eaw = ucd.join("EastAsianWidth.txt");
    let gc = ucd.join("DerivedGeneralCategory.txt");
    let emoji_presentation = set_of(&ucd.join("emoji-data.txt"), "Emoji_Presentation");

    let mut wide = vec![false; CODESPACE];
    for row in rows(&eaw) {
        let w = matches!(row.fields.first().map(String::as_str), Some("W" | "F"));
        for cp in row.first..=row.last {
            wide[cp as usize] = w;
        }
    }
    // `EastAsianWidth.txt`'s own header: unassigned code points in these blocks default to W, and
    // the file is not obliged to list them. At 17.0.0 it lists every one of them, so this fill
    // changes nothing — `the_default_wide_blocks_are_listed_explicitly` is the test that says when
    // that stops being true. The rule is kept because it is the file's documented semantics, not
    // because today's data needs it.
    for (first, last) in [
        (0x3400, 0x4DBF),
        (0x4E00, 0x9FFF),
        (0xF900, 0xFAFF),
        (0x2_0000, 0x2_FFFD),
        (0x3_0000, 0x3_FFFD),
    ] {
        wide[first..=last].fill(true);
    }

    let mut zero = vec![false; CODESPACE];
    for row in rows(&gc) {
        // Mn and Me are the zero-width marks; Cf is the format characters, ZWJ and the variation
        // selectors among them; Cc is the controls, which the engine never draws.
        let z = matches!(
            row.fields.first().map(String::as_str),
            Some("Mn" | "Me" | "Cf" | "Cc")
        );
        for cp in row.first..=row.last {
            zero[cp as usize] = z;
        }
    }

    (0..CODESPACE)
        .map(|cp| match (zero[cp], wide[cp] || emoji_presentation[cp]) {
            (true, _) => 0,
            (false, true) => 2,
            (false, false) => 1,
        })
        .collect()
}

// ---------------------------------------------------------------------------------------------
// The three-stage trie
// ---------------------------------------------------------------------------------------------

/// One built trie, and the size it costs.
struct Trie {
    leaf_shift: u32,
    mid_shift: u32,
    root: Vec<u16>,
    mid: Vec<Vec<u16>>,
    leaves: Vec<Vec<u8>>,
    bytes: usize,
}

impl Trie {
    /// Builds the trie for one split, deduplicating identical middle blocks and identical leaves.
    ///
    /// `bits` values are packed `8 / bits` to a byte, low bits first — the same packing
    /// `unicode-width` uses for its two-bit width codes.
    fn build(values: &[u8], bits: u32, leaf_shift: u32, mid_shift: u32) -> Trie {
        let per_byte = 8 / bits;
        let leaf_len = (1usize << leaf_shift) / per_byte as usize;
        let mid_len = 1usize << mid_shift;
        let root_shift = leaf_shift + mid_shift;

        let mut leaves: Vec<Vec<u8>> = Vec::new();
        let mut leaf_index: HashMap<Vec<u8>, u16> = HashMap::new();
        let mut mid: Vec<Vec<u16>> = Vec::new();
        let mut mid_index: HashMap<Vec<u16>, u16> = HashMap::new();
        let mut root: Vec<u16> = Vec::new();

        for block in values.chunks(1usize << root_shift) {
            let mut mid_block = Vec::with_capacity(mid_len);
            for leaf_values in block.chunks(1usize << leaf_shift) {
                let mut leaf = vec![0u8; leaf_len];
                for (i, v) in leaf_values.iter().enumerate() {
                    leaf[i / per_byte as usize] |= v << (bits * (i as u32 % per_byte));
                }
                let next = leaves.len() as u16;
                let id = *leaf_index.entry(leaf.clone()).or_insert_with(|| {
                    leaves.push(leaf);
                    next
                });
                mid_block.push(id);
            }
            let next = mid.len() as u16;
            let id = *mid_index.entry(mid_block.clone()).or_insert_with(|| {
                mid.push(mid_block);
                next
            });
            root.push(id);
        }

        let bytes = root.len() * idx_width(mid.len())
            + mid.len() * mid_len * idx_width(leaves.len())
            + leaves.len() * leaf_len;
        Trie {
            leaf_shift,
            mid_shift,
            root,
            mid,
            leaves,
            bytes,
        }
    }
}

/// A stage index is a `u8` while it fits in one, and a `u16` otherwise.
fn idx_width(count: usize) -> usize {
    if count <= u8::MAX as usize + 1 { 1 } else { 2 }
}

fn idx_type(count: usize) -> &'static str {
    if idx_width(count) == 1 { "u8" } else { "u16" }
}

/// Emits the smallest trie over the candidate splits, and its `#[inline]` lookup.
fn emit(out: &mut String, table: &str, func: &str, bits: u32, values: &[u8]) {
    // The codespace is 17 x 2^16, so a root stage wider than 2^16 code points would leave a short
    // final block and a ragged table. Every candidate below divides it exactly.
    let best = (4..=10)
        .flat_map(|leaf| (3..=8).map(move |mid| (leaf, mid)))
        .filter(|(leaf, mid)| leaf + mid <= 16)
        .map(|(leaf, mid)| Trie::build(values, bits, leaf, mid))
        .min_by_key(|trie| trie.bytes)
        .expect("no candidate splits");

    let mid_ty = idx_type(best.mid.len());
    let leaf_ty = idx_type(best.leaves.len());
    let mid_len = 1usize << best.mid_shift;
    let leaf_len = best.leaves[0].len();
    let per_byte = 8 / bits;

    // Every shift and mask the emitted lookup needs, named here so the generated body can be read
    // against the four stages it walks: root block, middle block, leaf byte, value within byte.
    let root_shift = best.leaf_shift + best.mid_shift;
    let mid_shift = best.leaf_shift;
    let mid_mask = mid_len - 1;
    let leaf_shift = per_byte.trailing_zeros();
    let leaf_mask = leaf_len - 1;
    let value_mask_in_byte = per_byte - 1;
    let value_mask = (1u8 << bits) - 1;
    let root_len = best.root.len();
    let mid_count = best.mid.len();
    let leaf_count = best.leaves.len();
    let bytes = best.bytes;
    let root = &best.root;
    let mid = &best.mid;
    let leaves = &best.leaves;

    let generated = format!(
        "\
/// {table}: a three-stage trie, {bits} bits per code point, {bytes} bytes of `.rodata`.
pub(crate) static {table}_ROOT: [{mid_ty}; {root_len}] = {root:?};
pub(crate) static {table}_MID: [[{leaf_ty}; {mid_len}]; {mid_count}] = {mid:?};
pub(crate) static {table}_LEAVES: [[u8; {leaf_len}]; {leaf_count}] = {leaves:?};

/// The {table} value of one code point. Three array indexes, no branch, no search.
#[inline]
pub(crate) fn {func}(cp: u32) -> u8 {{
    let root = {table}_ROOT[(cp >> {root_shift}) as usize];
    let leaf = {table}_MID[root as usize][((cp >> {mid_shift}) & {mid_mask}) as usize];
    let packed = {table}_LEAVES[leaf as usize][((cp >> {leaf_shift}) & {leaf_mask}) as usize];
    (packed >> ({bits} * (cp & {value_mask_in_byte}))) & {value_mask}
}}
"
    );
    out.push_str(&generated);
}
