//! **The composited frame as a picture, written rather than photographed.**
//!
//! A third reader of the same picture the reference compositor produces and the golden screens
//! compare: it walks the composited [`Surface`], resolves each cell's handles through the layer
//! stack's [`Tables`] and each colour through the terminal's [`Capabilities`], and writes SVG. No
//! terminal is in the loop, and nothing here re-composites — a picture that composited a second
//! time would be a picture of a different compositor.
//!
//! What that buys over a recording, and it is the whole reason the format is SVG rather than PNG:
//! the output is **text**, so a changed screen is a reviewable diff rather than a new binary blob;
//! it is **derived**, so it is regenerated by the same command that made it and cannot go stale
//! quietly; and it needs no emulator, no window server and no timing.
//!
//! # A run is a rectangle and a string, which is also what the wire is
//!
//! Cells are grouped into runs of one style along a row — the same grouping the serializer makes,
//! for the same reason — so a 300×80 screen is a few hundred elements rather than 24 000. Each run
//! is at most one `<rect>` (dropped when the run's background is the page's) and at most one
//! `<text>`, and the text carries `textLength` over the run's own columns: a viewer whose monospace
//! font has different metrics from the one named still puts every glyph in its cell.
//!
//! # What survives into the picture, and what cannot
//!
//! `EXPRESSION` below is that answer as a value rather than as a sentence, and the gate joins it to
//! a rendered picture. It is `cfg(test)`: it is the gate's population, and what a *caller* is owed
//! is on `Screen::to_svg`, which says the same three absences in prose. The three that do not survive are not oversights: **blink** is a property
//! of time and this is one instant, a **hyperlink** is a target and an SVG in a markdown file is not
//! a place to put one, and **conceal** survives by *not* drawing the glyph, which is the whole of
//! what it means.
//!
//! # The colours a terminal never told us
//!
//! [`Color::DEFAULT`] is *whatever this terminal paints with*, and a headless run has no terminal to
//! ask: `Capabilities::default_fg` and `default_bg` are `None` unless OSC 10 and 11 were answered.
//! A picture has to have a colour, so this states one — [`PAGE_FG`] and [`PAGE_BG`] — and that is a
//! declaration rather than a guess dressed as an answer: the sixteen indexed colours behave the same
//! way and are already resolved through the same table the quantiser uses, where the terminal's own
//! answers win and xterm's table is the fallback.

use std::fmt::Write as _;

use crate::caps::{Capabilities, Rgb};
use crate::cell::Cell;
use crate::mix::{Side, resolve};
use crate::style::{BOLD, CONCEAL, Color, DIM, ITALIC, OVERLINE, REVERSE, STRIKETHROUGH, Style};
use crate::surface::Surface;
use crate::tables::Tables;

/// One cell's width, in user units. The height is [`CELL_H`].
///
/// 0.6 em is the advance of every monospace face in the stack below at this size, and the whole
/// grid is derived from these two numbers so that nothing in the file is a magic coordinate.
const CELL_W: f32 = 9.6;
/// One row's height, in user units — 1.25 em, which is the line height a terminal uses.
const CELL_H: f32 = 18.0;
/// The type size the picture is drawn at.
const FONT_SIZE: f32 = 16.0;
/// Where the baseline sits inside a row, from its top.
const BASELINE: f32 = 14.0;
/// The margin around the grid, so that a descender on the last row is not clipped by the viewBox.
const PAD: f32 = 8.0;

/// The face stack. Named rather than embedded: a font file would be two orders of magnitude larger
/// than every picture in this repository put together, and `textLength` is what makes the metrics
/// not matter.
const FONT: &str = "ui-monospace,SFMono-Regular,Menlo,Consolas,\"DejaVu Sans Mono\",monospace";

/// The foreground a picture uses where the terminal never said what its own is.
pub(crate) const PAGE_FG: Rgb = Rgb::new(0xd0, 0xd4, 0xd8);
/// The background a picture uses where the terminal never said what its own is.
pub(crate) const PAGE_BG: Rgb = Rgb::new(0x14, 0x16, 0x1a);

/// How one thing a cell can carry reaches the picture.
#[cfg(test)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Expression {
    /// It is drawn, and this fragment appears in the picture when it is set.
    Drawn(&'static str),
    /// It is not drawn, for the stated reason. A picture that lies about one of these would be
    /// worse than a picture that omits it.
    Absent(&'static str),
}

/// **Every property a cell can carry, and what the picture does with it.**
///
/// The population is the style word plus the two things that are not in it — the cluster and its
/// width — and it is a value so that the gate can iterate it rather than a prose list somebody has
/// to remember to extend.
#[cfg(test)]
pub(crate) const EXPRESSION: &[(&str, Expression)] = &[
    ("fg indexed", Expression::Drawn("fill:#")),
    ("fg truecolor", Expression::Drawn("fill:#")),
    ("bg", Expression::Drawn("<rect")),
    ("bold", Expression::Drawn("font-weight:bold")),
    ("dim", Expression::Drawn("fill-opacity:.62")),
    ("italic", Expression::Drawn("font-style:italic")),
    ("reverse", Expression::Drawn("<rect")),
    ("strikethrough", Expression::Drawn("line-through")),
    ("overline", Expression::Drawn("overline")),
    ("underline", Expression::Drawn("text-decoration:underline")),
    ("underline double", Expression::Drawn("double")),
    ("underline curly", Expression::Drawn("wavy")),
    ("underline dotted", Expression::Drawn("dotted")),
    ("underline dashed", Expression::Drawn("dashed")),
    (
        "underline colour",
        Expression::Drawn("text-decoration-color"),
    ),
    ("a wide cluster", Expression::Drawn("textLength=\"19.2\"")),
    (
        "blink",
        Expression::Absent("a picture is one instant and blinking is a property of time"),
    ),
    (
        "conceal",
        Expression::Absent("it survives by the glyph not being drawn, which is what it means"),
    ),
    (
        "a hyperlink",
        Expression::Absent("the target is a place to go, and a picture is not a place to put one"),
    ),
];

/// The composited `surface` as an SVG document.
///
/// `tables` are the **layer stack's**, not the frame surface's: a composited frame is written into
/// and never drawn into, so its own interner is empty and every handle in it belongs to the stack.
pub(crate) fn render(surface: &Surface, tables: &Tables, caps: &Capabilities) -> String {
    let (w, h) = surface.size();
    let width = f32::from(w) * CELL_W + 2.0 * PAD;
    let height = f32::from(h) * CELL_H + 2.0 * PAD;
    let page_bg = resolve(caps, Color::DEFAULT, Side::Bg).unwrap_or(PAGE_BG);

    let mut out = String::with_capacity(1 << 14);
    let _ = write!(
        out,
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {} {}\" width=\"{}\" \
         height=\"{}\" font-family='{FONT}' font-size=\"{FONT_SIZE}\">\n\
         <rect width=\"{}\" height=\"{}\" fill=\"{}\"/>\n",
        round(width),
        round(height),
        round(width),
        round(height),
        round(width),
        round(height),
        hex(page_bg),
    );

    let mut scratch = [0u8; 4];
    for y in 0..h {
        let row = surface.row(y);
        let mut x = 0usize;
        while x < row.len() {
            let style = row[x].style;
            let mut end = x + 1;
            while end < row.len() && row[end].style.bits() == style.bits() {
                end += 1;
            }
            run(
                &mut out,
                &row[x..end],
                x as u16,
                y,
                style,
                tables,
                caps,
                page_bg,
                &mut scratch,
            );
            x = end;
        }
    }

    out.push_str("</svg>\n");
    out
}

/// One row-slice of cells sharing a style word.
#[expect(
    clippy::too_many_arguments,
    reason = "a run is a rectangle, a string and everything needed to resolve both; a struct here \
              would be the same eight values with a name in front of them"
)]
fn run(
    out: &mut String,
    cells: &[Cell],
    x: u16,
    y: u16,
    style: Style,
    tables: &Tables,
    caps: &Capabilities,
    page_bg: Rgb,
    scratch: &mut [u8; 4],
) {
    let ink = Ink::of(style, tables, caps);
    let left = PAD + f32::from(x) * CELL_W;
    let top = PAD + f32::from(y) * CELL_H;
    let columns = cells.len() as f32;

    if ink.bg != page_bg {
        let _ = write!(
            out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"{}\"/>",
            round(left),
            round(top),
            round(columns * CELL_W),
            round(CELL_H),
            hex(ink.bg),
        );
        out.push('\n');
    }

    if style.bits() & CONCEAL != 0 {
        return;
    }

    let mut text = String::new();
    for cell in cells {
        // A continuation carries no text of its own: the head before it is two columns wide and
        // `textLength` over the pair is what makes it occupy both.
        if cell.grapheme.is_continuation() {
            continue;
        }
        match tables.interner.render(cell.grapheme, scratch) {
            Some(s) => escape(&mut text, s),
            // An empty cell is one no layer painted. It is a hole in the picture and a space is the
            // honest thing to put in it: the terminal would show whatever was there before.
            None => text.push(' '),
        }
    }
    if text.trim_matches(' ').is_empty() && ink.decoration.is_none() {
        return;
    }

    let _ = write!(
        out,
        "<text x=\"{}\" y=\"{}\" textLength=\"{}\" lengthAdjust=\"spacingAndGlyphs\" \
         xml:space=\"preserve\" style=\"fill:{}{}\">{}</text>",
        round(left),
        round(top + BASELINE),
        round(columns * CELL_W),
        hex(ink.fg),
        ink.css(),
        text,
    );
    out.push('\n');
}

/// A style word resolved against a terminal: two colours and the CSS the attributes become.
struct Ink {
    fg: Rgb,
    bg: Rgb,
    bold: bool,
    dim: bool,
    italic: bool,
    decoration: Option<String>,
    decoration_style: Option<&'static str>,
    decoration_color: Option<Rgb>,
}

impl Ink {
    fn of(style: Style, tables: &Tables, caps: &Capabilities) -> Ink {
        let (fg, bg, ul) = match style.ext_handle() {
            None => (style.foreground(), style.background(), Color::DEFAULT),
            // A handle this table never minted cannot be resolved and must not be invented: the
            // default pair is what the terminal would paint with, which is what an unset word means.
            Some(handle) => match tables.exts.get(handle) {
                Some(e) => (e.fg, e.bg, e.ul),
                None => (Color::DEFAULT, Color::DEFAULT, Color::DEFAULT),
            },
        };
        let mut fg = resolve(caps, fg, Side::Fg).unwrap_or(PAGE_FG);
        let mut bg = resolve(caps, bg, Side::Bg).unwrap_or(PAGE_BG);
        let bits = style.bits();
        if bits & REVERSE != 0 {
            std::mem::swap(&mut fg, &mut bg);
        }

        let mut lines: Vec<&'static str> = Vec::new();
        if style.underline_style() != 0 {
            lines.push("underline");
        }
        if bits & STRIKETHROUGH != 0 {
            lines.push("line-through");
        }
        if bits & OVERLINE != 0 {
            lines.push("overline");
        }

        Ink {
            fg,
            bg,
            bold: bits & BOLD != 0,
            dim: bits & DIM != 0,
            italic: bits & ITALIC != 0,
            decoration: (!lines.is_empty()).then(|| lines.join(" ")),
            decoration_style: line_style(style.underline_style()),
            decoration_color: (ul != Color::DEFAULT)
                .then(|| resolve(caps, ul, Side::Fg))
                .flatten(),
        }
    }

    /// The declarations that follow `fill`, each with its leading semicolon.
    fn css(&self) -> String {
        let mut css = String::new();
        if self.bold {
            css.push_str(";font-weight:bold");
        }
        if self.dim {
            // Not a darker colour: dim is *this* colour, less of it, and a terminal that renders it
            // over a photograph gets the same answer.
            css.push_str(";fill-opacity:.62");
        }
        if self.italic {
            css.push_str(";font-style:italic");
        }
        if let Some(lines) = &self.decoration {
            let _ = write!(css, ";text-decoration:{lines}");
        }
        if let Some(kind) = self.decoration_style {
            let _ = write!(css, ";text-decoration-style:{kind}");
        }
        if let Some(c) = self.decoration_color {
            let _ = write!(css, ";text-decoration-color:{}", hex(c));
        }
        css
    }
}

/// The underline family, as CSS names it. `None` where the line needs no style of its own — no
/// underline at all, or the plain one, which is what `text-decoration: underline` already draws.
fn line_style(n: u8) -> Option<&'static str> {
    match n {
        2 => Some("double"),
        3 => Some("wavy"),
        4 => Some("dotted"),
        5 => Some("dashed"),
        _ => None,
    }
}

/// `#rrggbb`.
fn hex(c: Rgb) -> String {
    format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
}

/// A coordinate, with the trailing zeros of a whole number dropped.
///
/// The grid lands on tenths, so one decimal place is exact rather than rounded — and `19.2` for a
/// wide cluster's `textLength` is a number the gate below reads.
fn round(v: f32) -> String {
    let r = (v * 10.0).round() / 10.0;
    if (r - r.trunc()).abs() < f32::EPSILON {
        format!("{}", r.trunc() as i64)
    } else {
        format!("{r}")
    }
}

/// The three characters XML cannot carry in text content, and nothing else: a picture of a terminal
/// is mostly box-drawing and CJK, and escaping those to entities would triple the file for nothing.
fn escape(out: &mut String, s: &str) {
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(c),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::{Harness, pinned_extended};
    use crate::{Rect, Restyle, Style};

    /// Truecolor, because a headless screen is asked nothing and colour is narrowed to what the
    /// terminal can express: on the default harness every paint below would reach the frame as the
    /// terminal's own default and the picture would be right about a screen nobody drew.
    fn full(w: u16, h: u16) -> Harness {
        Harness::truecolor(w, h)
    }

    fn whole(h: &mut Harness, w: u16, rows: u16) -> crate::layer::LayerId {
        h.screen
            .layers()
            .add_content(0, Rect::new(0, 0, w, rows), true)
    }

    /// A picture of a screen with one of everything on it, which is what the join below reads.
    fn a_screen_with_one_of_everything() -> String {
        let mut h = full(40, 8);
        let id = whole(&mut h, 40, 8);
        {
            let mut view = h.screen.layers().view(id).expect("just added");
            view.text(
                0,
                0,
                "indexed",
                Style::new().fg(Color::indexed(11)).bg(Color::indexed(4)),
            );
            view.text(
                0,
                1,
                "truecolor",
                Style::new()
                    .fg(Color::rgb(0x33, 0x99, 0xff))
                    .bg(Color::rgb(0x20, 0x00, 0x40)),
            );
            view.text(0, 2, "bold", Style::new().bold());
            view.text(0, 3, "dim italic", Style::new().dim().italic());
            view.text(
                0,
                4,
                "reversed",
                Style::new().reverse().fg(Color::indexed(1)),
            );
            view.text(0, 5, "struck over", Style::new().strikethrough().overline());
            view.text(0, 6, "concealed", Style::new().conceal());
            // The wide cluster is drawn **alone**, so that it is a run of its own: a run is
            // grouped by style, and one that continued into the word beside it would carry the
            // word's columns in the `textLength` the gate reads.
            view.text(0, 7, "\u{6f22}", Style::new().blink());
            view.text(4, 7, "pulses", Style::new().blink());
        }
        h.screen.present();
        h.screen.to_svg()
    }

    /// The five underline spellings and a coloured one, which needs the extended channel.
    fn a_screen_of_underlines() -> String {
        let mut h = Harness::with_overrides(24, 6, pinned_extended());
        let id = whole(&mut h, 24, 6);
        {
            let mut view = h.screen.layers().view(id).expect("just added");
            for (row, style) in [
                Style::new().underline(),
                Style::new().underline_double(),
                Style::new().underline_curly(),
                Style::new().underline_dotted(),
                Style::new().underline_dashed(),
            ]
            .into_iter()
            .enumerate()
            {
                let y = i32::try_from(row).expect("five rows");
                view.text(0, y, "underlined", style.fg(Color::indexed(2)));
            }
            view.text(0, 5, "coloured", Style::new().underline());
            view.restyle(
                Rect::new(0, 5, 8, 1),
                &Restyle {
                    ul: Some(Color::rgb(9, 9, 9)),
                    ..Default::default()
                },
            );
        }
        h.screen.present();
        h.screen.to_svg()
    }

    #[test]
    fn every_expressed_property_reaches_the_picture_and_every_absent_one_does_not() {
        let everything = a_screen_with_one_of_everything();
        let underlines = a_screen_of_underlines();

        for (what, how) in EXPRESSION {
            if let Expression::Drawn(fragment) = how {
                assert!(
                    everything.contains(fragment) || underlines.contains(fragment),
                    "`{what}` is declared drawn as `{fragment}` and no picture contains it"
                );
            }
        }
        // The absent three, by the one thing each would have to leave behind.
        // Two needles, because SVG has two ways to make something blink and neither may be here:
        // a declaration, and an animation element. The word itself is not drawn on that row for
        // exactly the reason a scanner must not contain its own needle.
        assert!(!everything.contains("blink"), "blinking reached a picture");
        assert!(
            !everything.contains("<animate"),
            "a picture of one instant carries an animation"
        );
        assert!(
            !everything.contains("concealed"),
            "a concealed run drew its glyphs"
        );
        assert!(!everything.contains("<a "), "a hyperlink reached a picture");
    }

    /// A wide cluster occupies two columns and its continuation contributes no glyph of its own.
    #[test]
    fn a_wide_cluster_is_two_columns_of_one_glyph() {
        let mut h = full(6, 1);
        let id = whole(&mut h, 6, 1);
        {
            let mut view = h.screen.layers().view(id).expect("just added");
            view.text(0, 0, "\u{6f22}", Style::new().fg(Color::indexed(7)));
        }
        h.screen.present();
        let svg = h.screen.to_svg();
        assert!(
            svg.contains('\u{6f22}'),
            "the cluster itself is missing: {svg}"
        );
        assert_eq!(
            svg.matches('\u{6f22}').count(),
            1,
            "the continuation drew the head a second time"
        );
        assert!(
            svg.contains("textLength=\"19.2\""),
            "the cluster is not two columns wide: {svg}"
        );
    }

    /// The three characters XML cannot carry, and no fourth.
    #[test]
    fn markup_in_a_cell_is_escaped_and_nothing_else_is() {
        let mut h = full(12, 1);
        let id = whole(&mut h, 12, 1);
        {
            let mut view = h.screen.layers().view(id).expect("just added");
            view.text(0, 0, "<a & b>\u{2502}", Style::new());
        }
        h.screen.present();
        let svg = h.screen.to_svg();
        assert!(svg.contains("&lt;a &amp; b&gt;"), "{svg}");
        assert!(svg.contains('\u{2502}'), "a box-drawing rule was escaped");
    }

    /// A picture of a frame nothing drew into is the page and nothing else, which is the control for
    /// every count below: an element in it would be an element the frame did not ask for.
    #[test]
    fn an_empty_frame_is_one_rectangle() {
        let mut h = full(80, 24);
        h.screen.present();
        let svg = h.screen.to_svg();
        assert_eq!(svg.matches("<rect").count(), 1, "{svg}");
        assert_eq!(svg.matches("<text").count(), 0, "{svg}");
    }

    /// **The number the decision is owed.** One element per cell would be 24 000 on this screen;
    /// runs are what keep it in the hundreds, and the ceilings are round numbers well above what a
    /// screen like this costs rather than the measurement itself.
    #[test]
    fn the_largest_screen_the_budget_names_fits_in_its_ceiling() {
        let mut h = full(300, 80);
        let id = whole(&mut h, 300, 80);
        {
            let mut view = h.screen.layers().view(id).expect("just added");
            let row: String = std::iter::repeat_n('m', 300).collect();
            for y in 0..80i32 {
                let n = u8::try_from(y).expect("eighty rows");
                let style = if y % 2 == 0 {
                    Style::new().fg(Color::indexed(n))
                } else {
                    Style::new().bold().bg(Color::rgb(0, 0, n))
                };
                view.text(0, y, &row, style);
            }
        }
        h.screen.present();
        let svg = h.screen.to_svg();
        let elements = svg.matches("<rect").count() + svg.matches("<text").count();
        assert!(
            elements <= 400,
            "a 300x80 screen of eighty one-style rows drew {elements} elements"
        );
        assert!(
            svg.len() <= 128 * 1024,
            "a 300x80 screen is {} bytes",
            svg.len()
        );
    }

    /// The writer reads the composited frame and does not composite one of its own: two layers where
    /// the upper one wins put the upper one's cells in the picture.
    #[test]
    fn the_picture_is_the_composited_frame_and_not_the_lowest_layer() {
        let mut h = full(8, 1);
        let under = whole(&mut h, 8, 1);
        let over = h
            .screen
            .layers()
            .add_content(1, Rect::new(0, 0, 8, 1), true);
        {
            let mut view = h.screen.layers().view(under).expect("just added");
            view.text(0, 0, "under", Style::new());
        }
        {
            let mut view = h.screen.layers().view(over).expect("just added");
            view.text(0, 0, "OVER", Style::new());
        }
        h.screen.present();
        let svg = h.screen.to_svg();
        assert!(svg.contains("OVER"), "{svg}");
        assert!(!svg.contains("under"), "{svg}");
    }

    /// A screen with no terminal behind it has no answer for `Color::DEFAULT`, so the page is the
    /// stated pair — and the statement is what makes a headless picture reproducible.
    #[test]
    fn a_page_no_terminal_answered_for_is_the_stated_pair() {
        let mut h = Harness::new(10, 2);
        h.screen.present();
        assert!(h.screen.to_svg().contains(&hex(PAGE_BG)));
    }
}
