#!/usr/bin/env bash
# Is each committed recording still a recording of the thing it is a recording of?
#
#     scripts/recordings-gate.sh            # check, and fail saying which one drifted
#     scripts/recordings-gate.sh --bless    # re-record first, then run this
#
# # Why this exists, and why it is not `shots.sh --check`
#
# `shots.sh --check` re-takes all forty-nine SVGs and diffs them, which it can do because taking one
# is `cargo run -- --shot`: a single frame, written by this workspace's own code, deterministic.
# A GIF is not that. It is VHS driving a headless browser over a live terminal for thirteen seconds
# and ffmpeg assembling three hundred frames, it takes minutes, it needs two programs that are not
# cargo, and two runs of it are not byte-identical. Re-taking the recordings on every pipeline is not
# available, so this gate answers the cheaper question instead: **have the things that decide what
# the recording shows changed since it was made?**
#
# It exists because the answer was yes and nobody noticed. On 2026-09-15 `commander.rs` and `spf.rs`
# had their invented filesystem renamed, the SVG beside each was regenerated by `shots.sh` and the
# GIF was not — so the repository's own front page showed, for four days, a home directory and a
# shell prompt that no longer existed anywhere in the source. A review found it. Nothing else could
# have: the recordings were the one committed picture with no gate behind them.
#
# # What decides a recording, and what this therefore hashes
#
# Three files per tape, joined **by name** rather than listed, so a new tape arrives owing a line and
# a renamed one fails rather than being silently skipped:
#
#   docs/tapes/<n>.tape                  the script: what is typed, how long, at what size
#   crates/vitui-apps/examples/<n>.rs    the application: what it draws when that is typed
#   docs/img/apps/<n>.svg                that application's committed still
#
# The third is the interesting one. A change in `vitui-components` can alter what `commander` draws
# without touching `commander.rs`, and hashing the library instead would fire on every commit and
# teach everyone to re-bless without looking. The SVG is the cheap proxy: it is re-taken and diffed
# on every pipeline by `shots.sh --check`, so it is always a current picture of that application, and
# if the library changes what the application draws, the SVG moves and this gate moves with it.
#
# **Its limit is stated rather than mitigated**: an SVG is one frame at one state, so a library change
# that only alters something later in the recording — a dialog the tape opens on second 9 — moves
# neither the SVG nor this hash. That case is left to the eye, which is where it was before this
# file existed. What is closed is the case that actually happened.
#
# The recording's own hash is kept too, in a second column, so that replacing a GIF by hand is a
# different failure from letting one go stale, and so the two can be told apart in the message.
set -uo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
record="$root/docs/tapes/recorded.sha256"
bless=0
[ "${1:-}" = "--bless" ] && bless=1

# `sha256sum` is coreutils and is on every Linux runner here; macOS ships `shasum` and not that one.
# Either is fine — the file records whatever this produced, and the two agree on the digest.
if command -v sha256sum >/dev/null; then
  digest() { sha256sum "$@" | awk '{print $1}'; }
elif command -v shasum >/dev/null; then
  digest() { shasum -a 256 "$@" | awk '{print $1}'; }
else
  echo "recordings-gate: no sha256sum and no shasum, so nothing here can be hashed" >&2
  exit 1
fi

# The inputs' digest is a digest **of the three digests**, not of the concatenated files: that way it
# does not depend on the order bytes happen to be read in, and a file that becomes empty still moves
# it.
inputs_digest() {
  local n="$1"
  digest <(digest "$root/docs/tapes/$n.tape" \
                  "$root/crates/vitui-apps/examples/$n.rs" \
                  "$root/docs/img/apps/$n.svg")
}

shopt -s nullglob
tapes=("$root"/docs/tapes/*.tape)
shopt -u nullglob
if [ "${#tapes[@]}" -eq 0 ]; then
  echo "recordings-gate: no tapes under docs/tapes, so this gate has nothing to join against" >&2
  exit 1
fi

fresh=""
status=0

for tape in "${tapes[@]}"; do
  n="$(basename "$tape" .tape)"

  # The GIF's path is read out of the tape's own `Output` line rather than assumed from the name.
  # The tape is the declaration; a second one here could disagree with it.
  gif_rel=$(grep -m1 '^Output ' "$tape" | awk '{print $2}')
  gif="$root/$gif_rel"

  missing=0
  for f in "$root/docs/tapes/$n.tape" "$root/crates/vitui-apps/examples/$n.rs" \
           "$root/docs/img/apps/$n.svg" "$gif"; do
    if [ ! -f "$f" ]; then
      echo "recordings-gate: $n names $f and it is not there" >&2
      missing=1
      status=1
    fi
  done
  [ "$missing" -eq 1 ] && continue

  want_in=$(inputs_digest "$n")
  want_out=$(digest "$gif")
  fresh+="$n $want_in $want_out"$'\n'

  [ "$bless" -eq 1 ] && continue

  line=$(grep -m1 "^$n " "$record" 2>/dev/null || true)
  if [ -z "$line" ]; then
    echo "recordings-gate: $n has no line in docs/tapes/recorded.sha256 — a new tape owes one" >&2
    echo "recordings-gate: record it with 'docs/tapes/render.sh $tape', which blesses on success" >&2
    status=1
    continue
  fi
  have_in=$(echo "$line" | awk '{print $2}')
  have_out=$(echo "$line" | awk '{print $3}')

  if [ "$have_in" != "$want_in" ]; then
    echo "recordings-gate: $gif_rel is stale — the tape, the application or its still has changed" >&2
    echo "recordings-gate: re-record with 'docs/tapes/render.sh $tape'" >&2
    status=1
  elif [ "$have_out" != "$want_out" ]; then
    echo "recordings-gate: $gif_rel changed but nothing that decides it did" >&2
    echo "recordings-gate: restore it, or re-bless if the render itself was redone" >&2
    status=1
  else
    echo "recordings-gate: $gif_rel is current"
  fi
done

# An orphan line outlives the tape it was about and would otherwise sit there being true of nothing.
if [ "$bless" -eq 0 ] && [ -f "$record" ]; then
  while read -r n _; do
    [ -z "$n" ] && continue
    case "$n" in \#*) continue ;; esac
    if [ ! -f "$root/docs/tapes/$n.tape" ]; then
      echo "recordings-gate: recorded.sha256 has a line for $n and there is no such tape" >&2
      status=1
    fi
  done < "$record"
fi

if [ "$bless" -eq 1 ]; then
  {
    echo "# What each committed recording was made from, so that a stale one is a failure rather"
    echo "# than something a reader notices. Written by 'scripts/recordings-gate.sh --bless', which"
    echo "# 'docs/tapes/render.sh' runs for you on a successful render."
    echo "#"
    echo "# name  sha256(tape, example, still)  sha256(recording)"
    printf '%s' "$fresh"
  } > "$record"
  echo "recordings-gate: blessed ${#tapes[@]} recordings into docs/tapes/recorded.sha256"
fi

exit "$status"
